const colors = {
  light: {
    text: "#0a0f1e",
    tint: "#4f6ef7",
    background: "#f4f6ff",
    foreground: "#0a0f1e",
    card: "#ffffff",
    cardForeground: "#0a0f1e",
    primary: "#4f6ef7",
    primaryForeground: "#ffffff",
    secondary: "#e8ecff",
    secondaryForeground: "#1a2040",
    muted: "#e8ecff",
    mutedForeground: "#6b7ab0",
    accent: "#4f6ef7",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#dde2ff",
    input: "#dde2ff",
  },
  dark: {
    text: "#f0f4ff",
    tint: "#4f6ef7",
    background: "#0a0f1e",
    foreground: "#f0f4ff",
    card: "#141929",
    cardForeground: "#e8edff",
    primary: "#4f6ef7",
    primaryForeground: "#ffffff",
    secondary: "#1a2040",
    secondaryForeground: "#9ba8d0",
    muted: "#1a2040",
    mutedForeground: "#6b7ab0",
    accent: "#4f6ef7",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e2b50",
    input: "#1e2b50",
  },
  radius: 16,
};

export default colors;
